name: Auto Label for New Issues

on:
  issues:
    types: [opened]

jobs:
  label_new_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue matches template
        id: check_template
        run: |
          issue_body=$(curl -sL "${{ github.event.issue.url }}/body")
          if [[ $issue_body == *"<!-- template: GSSoC24 -->"* ]]; then
            echo "::set-output name=matches_template::true"
          else
            echo "::set-output name=matches_template::false"
          fi

      - name: Add label if issue matches template
        if: steps.check_template.outputs.matches_template == 'true'
        run: |
          gh issue add-labels ${{ github.event.issue.number }} GSSoC'24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
